export default function getProductData() {
    return '  {\n'
        + '    "name": "Kookose-karri kaste, gluteenivaba, laktoosivaba, FOODSTUDIO, 350 ml",\n'
        + '    "description": null,\n'
        + '    "url_key": "kookose-karri-kaste-gluteenivaba-laktoosivaba-foodstudio-350-ml"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Nisujahu T405, KALEW, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "nisujahu-t405-kalew-1-kg"\n'
        + '  },\n'


        + '  {\n'
        + '    "name": "Kamajahu, TARTU MILL, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "kamajahu-tartu-mill-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Nisujahu T550, KALEW, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "nisujahu-t550-kalew-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Riivsai, TARTU MILL, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "riivsai-tartu-mill-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Nisujahu eriti hea, VESKI MATI, 2 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "nisujahu-eriti-hea-veski-mati-2-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pannkoogijahu, VILMA, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pannkoogijahu-vilma-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Mahe kanamuna S, KIKERIKII ÖKOMUNA, 10tkg",\n'
        + '    "description": Good eggs for italian dish\n'
        + '    "url_key": "mahe-kanamuna-s-kikerikii-okomuna-10tk"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pille pisikesed pannkoogid, TARTU MILL, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pille-pisikesed-pannkoogid-tartu-mill-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Juubeli tordipulber, TARTU MILL, 450 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "juubeli-tordipulber-tartu-mill-450-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Prosciutto peekon viilutatud, RAKVERE LK, 140 g",\n'
        + '    "description": Prosciutto\n'
        + '    "url_key": "prosciutto-peekon-viilutatud-rakvere-lk-140-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Nisujahu T550, KALEW, 2 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "nisujahu-t550-kalew-2-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Itaalia pada, SALVEST, 530 g\n",\n'
        + '    "description": Itaalia pada,\n'
        + '    "url_key": "itaalia-pada-salvest-530-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Eriti hea nisujahu, VESKI MATI, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "eriti-hea-nisujahu-veski-mati-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Nisujahu T405, KALEW, 2 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "nisujahu-t405-kalew-2-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Tordipulber Juubeli, VILMA, 450 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "tordipulber-juubeli-vilma-450-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Ülepannikoogijahu, VILMA, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "ulepannikoogijahu-vilma-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Õhukesed pannkoogid, TARTU MILL, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "ohukesed-pannkoogid-tartu-mill-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Muffinid, TARTU MILL, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "muffinid-tartu-mill-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Plaadikook, TARTU MILL, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "plaadikook-tartu-mill-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pitsapõhjapulber, TARTU MILL, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pitsapohjapulber-tartu-mill-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Õhukese pitsapõhja pulber, VILMA, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "ohukese-pitsapohja-pulber-vilma-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pitsapõhjapulber, VILMA, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pitsapohjapulber-vilma-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "HULGI Nisujahu Eriti Hea 2tk, VESKI MATI, 2 x 2kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "hulgi-nisujahu-eriti-hea-2tk-veski-mati-2-x-2kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Nisujahu T550, VESKI MATI, 2 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "nisujahu-t550-veski-mati-2-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Kaerajahu purukook, TARTU MILL, 450 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "kaerajahu-purukook-tartu-mill-450-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Kartulipannkoogid, TARTU MILL, 200 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "kartulipannkoogid-tartu-mill-200-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Šokolaadimuffinipulber, VILMA, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "sokolaadimuffinipulber-vilma-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Durumnisujahupasta Fusilli, TARTU MILL, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "durumnisujahupasta-fusilli-tartu-mill-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pasta Cornetti, PRESTO, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pasta-cornetti-presto-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pasta durum Chiffari Lisci, TARTU MILL, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pasta-durum-chiffari-lisci-tartu-mill-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pasta Penne, PRESTO, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pasta-penne-presto-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pasta Chiffari Lisci Nr.183, PRESTO, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pasta-chiffari-lisci-nr-183-presto-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pasta Fusilli, PRESTO, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pasta-fusilli-presto-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Fusilli, PANZANI, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "fusilli-panzani-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Spiraal Fusilli international, PANZANI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "spiraal-fusilli-international-panzani-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Spagetid nr.7, PRESTO, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "spagetid-nr-7-presto-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Sarveke Chifferini, PANZANI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "sarveke-chifferini-panzani-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Durumnisujahupasta Penne, TARTU MILL, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "durumnisujahupasta-penne-tartu-mill-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pasta Fusilli, CAMPAGNA, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pasta-fusilli-campagna-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Durumnisujahust spagetid nr.7, TARTU MILL, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "durumnisujahust-spagetid-nr-7-tartu-mill-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Durumnisujahupasta Cornetti, TARTU MILL, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "durumnisujahupasta-cornetti-tartu-mill-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Specialita Penne Rigate, PANZANI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "specialita-penne-rigate-panzani-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Lintspagett Linguine, PANZANI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "lintspagett-linguine-panzani-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Merekarbid, PRESTO, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "merekarbid-presto-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Spagetid, CAMPAGNA, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "spagetid-campagna-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Specialita Farfalle, PANZANI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "specialita-farfalle-panzani-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Conchiglie Rigate teokarbid, PANZANI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "conchiglie-rigate-teokarbid-panzani-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Durum pasta Filini piccoli, TARTU MILL, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "durum-pasta-filini-piccoli-tartu-mill-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pasta durum Ditali Lisci, TARTU MILL, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pasta-durum-ditali-lisci-tartu-mill-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Macaroni, PANZANI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "macaroni-panzani-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Spagetid (nr.5), BARILLA, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "spagetid-nr-5-barilla-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Tatar, SELVER, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "tatar-selver-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Tatar 4 x 100 g, BALTIX, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "tatar-4-x-100-g-baltix-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Röstitud jämedad kaerahelbed, VESKI MATI, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "rostitud-jamedad-kaerahelbed-veski-mati-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Manna, VESKI MATI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "manna-veski-mati-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Tatar, VESKI MATI, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "tatar-veski-mati-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Täistera jämedad kaerahelbed, TARTU MILL, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "taistera-jamedad-kaerahelbed-tartu-mill-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Tatar, BALTIX, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "tatar-baltix-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Kaerakliid, TARTU MILL, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "kaerakliid-tartu-mill-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Tatar, VESKI MATI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "tatar-veski-mati-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Täisterakaerahelbed, HELEN, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "taisterakaerahelbed-helen-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Manna, TARTU MILL, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "manna-tartu-mill-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Kiirkeedu punane lääts, MÜLLERS MÜHLE, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "kiirkeedu-punane-laats-mullers-muhle-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Gluteenivabad suured täisterakaerahelbed, ELOVENA, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "gluteenivabad-suured-taisterakaerahelbed-elovena-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Odrakruup, TARTU MILL, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "odrakruup-tartu-mill-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Täistera jämedad kaerahelbed, TARTU MILL, 1kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "taistera-jamedad-kaerahelbed-tartu-mill-1kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Hirss, VESKI MATI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "hirss-veski-mati-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Hernes kollane poolik, BALTIX, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "hernes-kollane-poolik-baltix-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Toortatar, BALTIX, 4x100 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "toortatar-baltix-4x100-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Hirss, BALTIX, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "hirss-baltix-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "HULGI Röstitud jämedad kaerahelbed, VESKI MATI, 2 x 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "hulgi-rostitud-jamedad-kaerahelbed-veski-mati-2-x-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Eesti toortatratang, REMEDYWAY, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "eesti-toortatratang-remedyway-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Kinoa valge, JUST NATURE, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "kinoa-valge-just-nature-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Maisitang, VESKI MATI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "maisitang-veski-mati-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Odrakruup, BALTIX, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "odrakruup-baltix-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pikateraline riis 4 x 125 g, BOSTO, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pikateraline-riis-4-x-125-g-bosto-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Basmati riis 4 x 125 g, BOSTO, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "basmati-riis-4-x-125-g-bosto-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Tai jasmiiniriis 4 x 125 g, BOSTO, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "tai-jasmiiniriis-4-x-125-g-bosto-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Basmati riis, VESKI MATI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "basmati-riis-veski-mati-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Sõmer riis, VESKI MATI, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "somer-riis-veski-mati-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Risotoriis, VESKI MATI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "risotoriis-veski-mati-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Küüslauk, kg",\n'
        + '    "description": "Küüslauk",\n'
        + '    "url_key": "kuuslauk-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pruun riis 4 x 125 g, BOSTO, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pruun-riis-4-x-125-g-bosto-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pikateraline riis, BALTIX, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "pikateraline-riis-baltix-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pikateraline riis, BALTIX, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pikateraline-riis-baltix-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Täistera pruun riis, VESKI MATI, 400 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "taistera-pruun-riis-veski-mati-400-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pikateraline riis 8 x 125 g, BOSTO, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "pikateraline-riis-8-x-125-g-bosto-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pudruriis, VESKI MATI, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "pudruriis-veski-mati-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pikateraline riis, VESKI MATI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pikateraline-riis-veski-mati-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Aurutatud riis, BALTIX, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "aurutatud-riis-baltix-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Basmati riis 4 x 75 g, BOSTO, 300 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "basmati-riis-4-x-75-g-bosto-300-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pikateraline riis, TARTU MILL, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "pikateraline-riis-tartu-mill-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pruun Basmati riis 4x125g, BOSTO, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pruun-basmati-riis-4x125g-bosto-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pudruriis (Ümarateraline riis), BALTIX, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "pudruriis-umarateraline-riis-baltix-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Jasmiiniriis, VESKI MATI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "jasmiiniriis-veski-mati-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Eelkeedetud sõmer riis, TARTU MILL, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "eelkeedetud-somer-riis-tartu-mill-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pikateraline riis 4 x 125 g, BEN\'S ORIGINAL, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pikateraline-riis-4-x-125-g-ben-s-original-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Riis aurutatud (sõmer) 4x125g, TARTU MILL, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "riis-aurutatud-somer-4x125g-tartu-mill-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Pikateraline riis 4 x 125 g, DORIS, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "pikateraline-riis-4-x-125-g-doris-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Risotoriis Arborio, RISO SCOTTI, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "risotoriis-arborio-riso-scotti-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Kikerherne jahu, PAPA, 1 kg",\n'
        + '    "description": null,\n'
        + '    "url_key": "kikerherne-jahu-papa-1-kg"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Müslibatoon jõhvika- vaarika, SANTE, 40 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "muslibatoon-johvika-vaarika-sante-40-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Müslibatoon šokolaadi-banaani, CORNY BIG, 50 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "muslibatoon-sokolaadi-banaani-corny-big-50-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Banaani-müslibatoon, šokolaadikattega, SANTE,",\n'
        + '    "description": null,\n'
        + '    "url_key": "banaani-muslibatoon-sokolaadikattega-sante"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Kaerahelbe kiirpuder metsamarjadega, VESKI MATI, 45 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "kaerahelbe-kiirpuder-metsamarjadega-veski-mati-45-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Täistera kiirkaerahelbed, TARTU MILL, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "taistera-kiirkaerahelbed-tartu-mill-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Täistera röstitud kiirtatrahelbed, TARTU MILL, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "taistera-rostitud-kiirtatrahelbed-tartu-mill-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Müslibatoon jõhvikatega, CORNY BIG, 50 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "muslibatoon-johvikatega-corny-big-50-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Hommikusöögihelbed KitKat, NESTLÉ, 330 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "hommikusoogihelbed-kitkat-nestle-330-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Hommikusöögibatoon Fitness Jõhvika-Maasika, NESTLÉ, 23,5 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "hommikusoogibatoon-fitness-johvika-maasika-nestle-23-5-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Kiirpuder Mustika, VESKI MATI, 45 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "kiirpuder-mustika-veski-mati-45-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Röstitud müsli banaani-šokolaadi, SANTE, 350 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "rostitud-musli-banaani-sokolaadi-sante-350-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Müslibatoon piimašokolaadiga, CORNY BIG, 50 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "muslibatoon-piimasokolaadiga-corny-big-50-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Hommikusöögibatoon Nesquik, NESTLÉ, 25 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "hommikusoogibatoon-nesquik-nestle-25-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Krõbe müsli tumeda šokolaadiga, SANTE, 350 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "krobe-musli-tumeda-sokolaadiga-sante-350-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Kiirkaerahelbed, NORDIC, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "kiirkaerahelbed-nordic-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Hommikusöögibatoon Fitness Šokolaadiga, NESTLÉ, 23,5g",\n'
        + '    "description": null,\n'
        + '    "url_key": "hommikusoogibatoon-fitness-sokolaadiga-nestle-23-5g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Kamapallid, BALSNACK, 150 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "kamapallid-balsnack-150-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Riisihelbed, TARTU MILL, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "riisihelbed-tartu-mill-500-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Müslibatoon piima-kakaotäidisega, CORNY BIG, 40 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "muslibatoon-piima-kakaotaidisega-corny-big-40-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Müslibatoon kookose-šokolaadi, CORNY BIG, 50 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "muslibatoon-kookose-sokolaadi-corny-big-50-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Müslibatoon šokolaadi ja maapähkli, CORNY BIG, 50 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "muslibatoon-sokolaadi-ja-maapahkli-corny-big-50-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Parmigiano reggiano KPN, GRANAROLO, 200 g",\n'
        + '    "description": "Parmigiano reggiano kpn juust 200g",\n'
        + '    "url_key": "parmigiano-reggiano-kpn-granarolo-200-g"\n'
        + '  },\n'
        + '  {\n'
        + '    "name": "Kiirkaerahelbed, HELEN, 500 g",\n'
        + '    "description": null,\n'
        + '    "url_key": "kiirkaerahelbed-helen-500-g"\n'
        + '  },'
        + '{"name":"Peeneteraline jodeeritud mineraalsool, MEIRA, 80 g","description":null,"url_key":"peeneteraline-jodeeritud-mineraalsool-meira-80-g"}\n,'
        + '{"name":"Durumnisujahust spagetid nr.7, TARTU MILL, 500 g","description":null,"url_key":"durumnisujahust-spagetid-nr-7-tartu-mill-500-g"}\n,'
        + '{"name":"Toorjuust Mascarpone, EUROSER, 500 g","description":null,"url_key":"toorjuust-mascarpone-euroser-500-g"}\n,'
        + '{"name":"Vähendatud rasvasisaldusega kakaopulber, VILMA, 150 g","description":null,"url_key":"vahendatud-rasvasisaldusega-kakaopulber-vilma-150-g"}\n,'
        + '{"name":"Pitsapõhjapulber, TARTU MILL, 400 g","description":null,"url_key":"pitsapohjapulber-tartu-mill-400-g"}\n,'
        + '{"name":"Penne Rigate torukesed, BARILLA, 500 g","description":null,"url_key":"penne-rigate-torukesed-barilla-500-g"}\n,'
        + '{"name":"Tiramisu küpsised, MATILDE VICENZI, 200 g","description":null,"url_key":"tiramisu-kupsised-matilde-vicenzi-200-g"},\n'
        + '        {"name":"Purustatud must pipar, SANTA MARIA, 18 g","description":null,"url_key":"purustatud-must-pipar-santa-maria-18-g"},\n'
        + '                {"name":"Basmati riis, RISO SCOTTI, 500 g","description":null,"url_key":"basmati-riis-riso-scotti-500-g"}\n'
        + '                ,\n'
        + '                {"name":"Pruun riis, BALTIX, 4x100 g","description":null,"url_key":"pruun-riis-baltix-4x100-g"}\n'
        + '                ,\n'
        + '                {"name":"Arborio Risotoriis, JULIETTA, 1 kg","description":null,"url_key":"arborio-risotoriis-julietta-1-kg"},\n'
        + '                        {"name":"Mugulsibul pakitud võrgus, 1 kg","description":null,"url_key":"mugulsibul-pakitud-vorgus-1-kg"},\n'
        + '                                {"name":"Šalottsibul võrgus, 250 g","description":null,"url_key":"salottsibul-vorgus-250-g"}';
}
